#!/usr/bin/env bash
# displays the PID, along with the process name, of processes
# whose name contain the word bash

pgrep -l bash
Footer
© 2023 GitHub, Inc.
Footer navigation
Terms
Privacy
Security
